import React from 'react';
import { MissionExecutionResult, CarePlanCreated } from '../../types/agent';
import {
  IconAlertTriangle,
  IconClockHistory,
  MissionStatusBadge,
  formatDateTime,
} from './missionUi';
import { MissionOutcomeDisplay } from './MissionOutcomeDisplay';

interface MissionDetailPanelProps {
  mission: MissionExecutionResult;
  generatedCarePlans: CarePlanCreated[];
  onSelectCarePlan: (carePlan: CarePlanCreated) => void;
  onDragStart?: React.TouchEventHandler<HTMLDivElement>;
  onDragMove?: React.TouchEventHandler<HTMLDivElement>;
  onDragEnd?: React.TouchEventHandler<HTMLDivElement>;
  isDragging?: boolean;
}

export const MissionDetailPanel: React.FC<MissionDetailPanelProps> = ({
  mission,
  generatedCarePlans,
  onSelectCarePlan,
  onDragStart,
  onDragMove,
  onDragEnd,
  isDragging = false,
}) => (
  <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
    <div
      className={`px-6 py-5 border-b border-gray-100 ${onDragStart ? 'cursor-grab touch-none select-none active:cursor-grabbing' : ''}`}
      onTouchStart={onDragStart}
      onTouchMove={onDragMove}
      onTouchEnd={onDragEnd}
      style={isDragging ? { cursor: 'grabbing' } : undefined}
    >
      {onDragStart && (
        <div className="mx-auto mb-3 h-1.5 w-12 rounded-full bg-gray-300" />
      )}
      <div className="flex items-center gap-2 mb-1.5 flex-wrap">
        <h2 className="text-base font-semibold text-gray-900">
          Mission Detail
        </h2>
        <MissionStatusBadge status={mission.status} />
      </div>
      <p className="text-sm text-gray-600">{mission.goal}</p>
      <p className="text-xs text-gray-400 mt-1.5 font-mono">
        {mission.missionId}
      </p>
      <p className="text-xs text-gray-400 mt-0.5">
        Started {formatDateTime(mission.startedAt)}
        {mission.completedAt &&
          ` · Completed ${formatDateTime(mission.completedAt)}`}
      </p>
    </div>

    <div className="px-6 py-5 space-y-5">
      {mission.failureReason && (
        <div className="flex items-start gap-3 text-sm text-red-700 bg-red-50 border border-red-100 rounded-lg px-4 py-3">
          <IconAlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
          <span>{mission.failureReason}</span>
        </div>
      )}

      {mission.outputs?.response && (
        <div>
          <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-2">
            Outcome
          </h3>
          <MissionOutcomeDisplay
            response={mission.outputs.response}
            cohortMetrics={mission.outputs.cohortMetrics}
          />
        </div>
      )}

      <div>
        <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-2">
          Generated Care Plans
        </h3>
        {generatedCarePlans.length === 0 ? (
          <p className="text-sm text-gray-500">
            {mission.status === 'COMPLETED'
              ? 'No care plans were generated by this mission.'
              : 'Care plans will appear here once the mission completes.'}
          </p>
        ) : (
          <div className="space-y-2">
            {generatedCarePlans.map((carePlan, idx) => (
              <button
                key={carePlan.carePlanId || idx}
                onClick={() => onSelectCarePlan(carePlan)}
                className="w-full text-left p-4 bg-gray-50 border border-gray-200 rounded-lg hover:shadow-md hover:border-blue-300 transition-all group"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    {carePlan.name && carePlan.name.trim() ? (
                      <>
                        <p className="text-xs text-gray-700 font-medium mb-1">
                          {carePlan.name}
                        </p>
                        <div className="text-xs text-gray-500 space-y-0.5 mb-2">
                          {carePlan.mrn && <p>MRN: {carePlan.mrn}</p>}
                          {carePlan.gender && <p>Gender: {carePlan.gender}</p>}
                          {carePlan.dob && <p>DOB: {carePlan.dob}</p>}
                        </div>
                        <h4 className="font-medium text-gray-900 group-hover:text-blue-600 transition-colors text-sm">
                          Care Plan
                        </h4>
                      </>
                    ) : (
                      <h4 className="font-medium text-gray-900 text-sm mb-2">
                        Care Plan
                      </h4>
                    )}
                    <p className="text-xs text-gray-400 font-mono truncate">
                      {carePlan.carePlanId}
                    </p>
                  </div>
                  <span className="inline-flex items-center px-2.5 py-1.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700 whitespace-nowrap">
                    View / Edit
                  </span>
                </div>
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  </div>
);

export const EmptyMissionDetail: React.FC = () => (
  <div className="h-full py-24 px-6 flex flex-col items-center text-center justify-center">
    <div className="h-12 w-12 rounded-full bg-gray-100 text-gray-400 flex items-center justify-center mb-3">
      <IconClockHistory className="h-6 w-6" />
    </div>
    <h3 className="text-sm font-semibold text-gray-700 mb-1">
      Select a mission
    </h3>
    <p className="text-sm text-gray-500 max-w-xs">
      Choose one from the list to see its full outcome and generated care plans.
    </p>
  </div>
);
